server:
  port: 9527

spring:
  application:
    name: cloud-gateway #\u4EE5\u5FAE\u670D\u52A1\u6CE8\u518C\u8FDBconsul\u6216nacos\u670D\u52A1\u5217\u8868\u5185
  cloud:
    consul: #\u914D\u7F6Econsul\u5730\u5740
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                 #\u8DEF\u7531\u7684ID(\u7C7B\u4F3Cmysql\u4E3B\u952EID)\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          # uri: http://localhost:8001               #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          uri: lb://cloud-payment-service            #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/pay/gateway/get/**               # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
            # - After=2024-04-06T17:05:30.079998400+08:00[Asia/Shanghai]
            # - Cookie=username,zzyy
            # - Header=X-Request-ID, \d+
            # - Host=**.cnowse.com
            # - Query=username, \d+
            # - RemoteAddr=192.168.2.1/24
            - My=diamond
            # - name: My
            #   args:
            #     userType: diamond

        - id: pay_routh2 #pay_routh2                 #\u8DEF\u7531\u7684ID(\u7C7B\u4F3Cmysql\u4E3B\u952EID)\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          uri: http://localhost:8001                 #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/pay/gateway/info/**              # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
          filters:
            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
            - RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
            - SetRequestHeader=user-agent, iPhone/15PM